### ISSUE TITLE
data-* rendered with double quotes

### ISSUE THREAD

**Issue by mhrisse** [sisoftrg/jade.php#10]
Hi! 

First of all, thumbs up for the port to PHP! Works like a charm to use it on client and server. I have a little problem with html5 data-attributes tho:

``` php
div(data-module="#{mod}", class="#{module_classes}") 
```

renders as 

``` php
<div data-module=""something"" class="some classes here">
```

Please notice the double quotes around the data-module value.
The problem only happens with a variable + data- attributes. 

``` php
div(data-module="something", class="#{module_classes}") 
```

OK, constant works as expected

``` php
div(module="#{mod}", class="#{module_classes}") 
```

OK, as expected, but of course creates invalid html.

It works perfectly with Jade client-side. Might there be a
Javascript + not ported or something?

Any help appreciated!

**Comment by sisoftrg** [comment]
fixed with last commit.

also, you can use something like

``` jade
div(data-module=mod, class=module_classes) 
```

but it without escaping.

**Comment by mhrisse** [comment]
Works perfectly now. Thanks!
