### ISSUE TITLE
Scope Resolution :: Error

### ISSUE THREAD

**Issue by delphaber** [sisoftrg/jade.php#8]
Hi :)

This line:
`= Yii::app()->request->baseUrl`

is translated in a wrong way:

``` php
<?php $__=$Yii::app();echo htmlspecialchars($__) ?>
```

This line:
`- $baseUrl = Yii::app()->request->baseUrl`

is translated in the right way:

``` php
<?php $baseUrl = Yii::app()->request->baseUrl ?>
```

No problem with this too:

``` php
- $app = Yii::app()
= $app->request->baseurl
```

I think the bug is due to the php scope resolution operator ::

**Comment by sisoftrg** [comment]
fixed.

**Comment by delphaber** [comment]
Thx!
